### ISSUE TITLE
[BUG] Not installing in Docker Windows

### ISSUE THREAD

**Issue by Command-Conquer** [guillaumebriday/laravel-blog#103]
Hi... thanks for your work... i dont know exactly if its a bug or something related about my setup. I am using docker 19.03.1 and docker-compose 1.24.1, everything was smooth till...

## Describe the bug
In your installation instrucitons after artisan storage:link i get an
ErrorException 
symlink(): Protocol error
at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:263

and after

 docker run --rm -it -v $(pwd):/app -w /app node yarn i get an

C:\Program Files\Docker Toolbox\docker.exe: invalid reference format.

Im newbie using docker so i dont know what is happening here.... anyway...

Thanks for your time and work

**Comment by guillaumebriday** [comment]
Hum I don't plan to support this project on Windows unfortunately. Maybe you should try on WSL
