### ISSUE TITLE
Resend activation link returns error

### ISSUE THREAD

**Issue by upcoders** [guillaumebriday/laravel-blog#104]
When click on resend verification link, I get following error:
`The GET method is not supported for this route. Supported methods: POST.`

How can I resolve this?

Thanks

**Comment by guillaumebriday** [comment]
Hey, I need to try maybe it's a mistake

**Comment by guillaumebriday** [comment]
Fix: https://github.com/guillaumebriday/laravel-blog/commit/b915b82fbcea87cac32ab2e5506da4640e61fd24

Thank you!
