### ISSUE TITLE
Switch from Docker to Homestead

### ISSUE THREAD

**Issue by guillaumebriday** [guillaumebriday/laravel-blog#111]
I would like to remove Docker and use Homestead.

Docker is not easy to learn and could be hard for beginner to start with.

[Homestead](https://laravel.com/docs/8.x/homestead) is the default environment for Laravel and should be easier to use if you just want to learn Laravel in the first place.

**Comment by aimalamiri** [comment]
Homestead is only working in Mac, what about Windows and Linux?

**Comment by guillaumebriday** [comment]
@aimalamiri I think you're thinking about [Valet](https://laravel.com/docs/8.x/valet) not Homestead

**Comment by aimalamiri** [comment]
Oh yes, but still I think docker is better than vagrant, cause lots of developers are familiar with docker.

**Comment by guillaumebriday** [comment]
I don't think so tdh. Docker is used by lots of **experimented** developers and is not officially supported by Laravel.

If you want want to learn PHP / Laravel, you'd better go with the default development environment. An experimented developer would know how to setup Docker if they want to go with it.

Moreover, Docker performances on macOS are pretty terrible compared to VM.

I think this project should stick with Laravel default choices. I created it to show what Laravel can do in the first place. Homestead if documented in the Laravel documentation, not Docker.

Thank you though for your comment! 👍
