### ISSUE TITLE
Upgrade to Laravel 8

### ISSUE THREAD

**Issue by guillaumebriday** [guillaumebriday/laravel-blog#112]

**Comment by bigtata** [comment]
Hello, I can try to help you, I just discovered your project, will install it now and start a branch with laravel 8 soon after. Have you start poking around the update ? I'll start with https://laravel.com/docs/8.x/upgrade :)

**Comment by guillaumebriday** [comment]
Yes I did most of the job, but I'm stuck with the upgrade of `spatie/laravel-medialibrary` to 8.x because to upgrade  [doc is not really helpful](https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#from-v7-to-v8)

That's would be great of you could help me to upgrade this library so I could merge the complete Laravel 8 upgrade!

Thanks a lot @bigtata !

**Comment by aimalamiri** [comment]
@guillaumebriday Did you tried with reinstalling the package
`composer remove spatie/laravel-medialibrary`
`composer require spatie/laravel-medialibrary'

**Comment by guillaumebriday** [comment]
Yep, but the code need to be changed too :/

**Comment by aimalamiri** [comment]
Check this one.

https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md

**Comment by guillaumebriday** [comment]
I know. My issue is this sentence: `Take a look in the source code of medialibrary what the new namespace of the class is and use that.`

I don't understand how they ended up writing this thinking it was helpful...

I naively tried to update but I still have errors and not so much time to dive into them. :/

**Comment by guillaumebriday** [comment]
https://github.com/guillaumebriday/laravel-blog/commit/3271480c121855b881eabcab7eb19dcd5c4e3fa7
