### ISSUE TITLE
error on fresh install

### ISSUE THREAD

**Issue by jahstation** [guillaumebriday/laravel-blog#115]
hi to all
while im running vagrant ssh, after runs all commands of installion,  i see this error when I try to visit the home page:

>  ErrorException (E_ERROR)
The Mix manifest does not exist. (View: /home/vagrant/code/resources/views/layouts/app.blade.php) (View: /home/vagrant/code/resources/views/layouts/app.blade.php)

ive tried to used 'npm install' with several errors...

**Comment by alighasemzadeh** [comment]
@jahstation 
Use Yarn.

**Comment by guillaumebriday** [comment]
All the commands to run are in the readme. npm is not meant to be used here.

**Comment by guillaumebriday** [comment]
thanks @alighasemzadeh
