### ISSUE TITLE
[BUG] npm install error

### ISSUE THREAD

**Issue by alighasemzadeh** [guillaumebriday/laravel-blog#116]
When I use npm install 
I get:

>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: eslint@7.8.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.8.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"6.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by alighasemzadeh** [comment]
@guillaumebriday please guide me.

**Comment by guillaumebriday** [comment]
Hey

Yarn is the default package manager in this project. and check if you are in the lts version of node

**Comment by aboulmaaly** [comment]
this video can help you:
https://youtu.be/QeRUXYRnP_8
