### ISSUE TITLE
 in windows : composer install: it is missing from your system. Install or enable PHP's pcntl extension.

### ISSUE THREAD

**Issue by saber13812002** [guillaumebriday/laravel-blog#122]
as documented in the readme. file 👍 in windows 10

after clone when run composer install this error happened:

```
 composer require laravel/horizon
Using version ^5.7 for laravel/horizon
./composer.json has been updated
Running composer update laravel/horizon
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/horizon[v5.7.0, ..., 5.x-dev] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - Root composer.json requires laravel/horizon ^5.7 -> satisfiable by laravel/horizon[v5.7.0, ..., 5.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside the terminal to see which files are used by PHP in CLI mode.
```

## Description:
after clone when run composer install this error happened:

## To Reproduce
1. clone
2. go to cloned repo folder
3. cp .env.example .env
4. run composer i
5. see the error

## Expected behavior
composer install run successfully then Horizon install carefully  on windows

**Comment by saber13812002** [comment]
for now, I remove horizon and run composer I to find a better solution

composer remove laravel/horizon

composer i

**Comment by guillaumebriday** [comment]
You need to install the `pcntl` extension. I have no idea how to do that on Windows though.

I cannot recommend windows as development environment, you should try on WSL2 👍
