### ISSUE TITLE
[BUG] Systax Error in channels.php

### ISSUE THREAD

**Issue by DungBuiDeveloper** [guillaumebriday/laravel-blog#123]
I'm not sure if this is an error but I find the syntax strange

<img width="972" alt="Screenshot at Dec 30 13-23-16" src="https://user-images.githubusercontent.com/36411020/147727107-883e050c-2fb7-4728-a85a-1d4ef950f712.png">

And how about fix code below

`Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});`

**Comment by guillaumebriday** [comment]
You mean this syntax https://stitcher.io/blog/short-closures-in-php?
