### ISSUE TITLE
Is this Open source project getting update ?[Request]

### ISSUE THREAD

**Issue by james-wong123** [guillaumebriday/laravel-blog#125]
This is definitely a magnificent open-source project for beginners to get deeper into laravel, but it seems like it's not getting updated. Would be really nice to see it once more time! **@guillaumebriday**

**Comment by guillaumebriday** [comment]
@james-wong123 There you go https://github.com/guillaumebriday/laravel-blog/commit/f118ed76578d81cd1aaa6d656ca15d721cb55765

- Still need to upgrade to Bootstrap 5 and Vue 3.
- Could be nice to use new php 8/8.1 features. 
- Could be nice to use new Laravel features and new functions. 

Thanks 👍

**Comment by james-wong123** [comment]
@guillaumebriday, Thx a lot !!!!!!!!

**Comment by guillaumebriday** [comment]
In fact, I'm not really in the PHP ecosystem anymore so myuch, so if you know some cool stuff that Laravel has added between 8.x and 9.x and the same for PHP, that would be nice! 🙏

**Comment by james-wong123** [comment]
what ecosystem that you are currently working with? python?

**Comment by guillaumebriday** [comment]
@james-wong123 I've been in the Rails ecosystem since 2015 👍 and it's so awesome that I don't want to leave it
