### ISSUE TITLE
Migration error (2022_04_30_011124_add_generated_conversions_to_media_table) in MySQL

### ISSUE THREAD

**Issue by gludovatza** [guillaumebriday/laravel-blog#131]
https://github.com/guillaumebriday/laravel-blog/blob/aebc310059ea0301093b491a690eed092899dc7b/database/migrations/2022_04_30_011124_add_generated_conversions_to_media_table.php#L32

The correct code is:
'generated_conversions' => DB::raw("JSON_EXTRACT(custom_properties, '$.generated_conversions')"),
via https://github.com/spatie/laravel-medialibrary/blob/main/UPGRADING.md

**Comment by guillaumebriday** [comment]
You're right! 🙏 

But I still got an error, any idea why?

<img width="1470" alt="Screenshot 2023-08-22 at 01 15 15" src="https://github.com/guillaumebriday/laravel-blog/assets/8252238/e65af463-9e00-49d1-bf67-ff068a741b12">
