### ISSUE TITLE
composer ? and what is your suggestion for the database ?

### ISSUE THREAD

**Issue by aschhkan** [guillaumebriday/laravel-blog#149]
I'm a new student in the web developer field and I need more help. Thank you very much
I have an error message for php artisan... should I install composer? Another question is how (yarn) can install or work.

**Comment by guillaumebriday-pa** [comment]
Hi @aschhkan 

Did you read this section in the readme before? https://github.com/guillaumebriday/laravel-blog#installation

I think you can get everything you need to install the project on your own machine 👍
