### ISSUE TITLE
If the locale is not French, the test will fail.

### ISSUE THREAD

**Issue by ivoth** [guillaumebriday/laravel-blog#15]
Some of the tests are fixed French.

**Comment by guillaumebriday** [comment]
Hey ! I will fix that. In the next release the default language will be English 👍

**Comment by ivoth** [comment]
Can  use localized languages in tests?
Also, can the default account be added to the configuration?
Thanks

**Comment by guillaumebriday** [comment]
🤔 I don't think it's a good practice because if a key is not defined the tests will be green anyway.

I want to tests the complete response. I'm going to translate the tests in a next PR. 👍

**Comment by guillaumebriday** [comment]
Fixed : https://github.com/guillaumebriday/laravel-blog/commit/4a7d67d836a96a65136d51b3f34096a6a95f42ec
