### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by pouria-azad** [guillaumebriday/laravel-blog#156]
When I run the 'php artisan', I get the following errors:

PHP Fatal error:  Uncaught Error: Class "Illuminate\Foundation\Application" not found in C:\Users\ARTA\Desktop\laravel-blog\bootstrap\app.php:14
Stack trace:
#0 C:\Users\ARTA\Desktop\laravel-blog\artisan(20): require_once()
#1 {main}
  thrown in C:\Users\ARTA\Desktop\laravel-blog\bootstrap\app.php on line 14

Fatal error: Uncaught Error: Class "Illuminate\Foundation\Application" not found in C:\Users\ARTA\Desktop\laravel-blog\bootstrap\app.php:14
Stack trace:
#0 C:\Users\ARTA\Desktop\laravel-blog\artisan(20): require_once()
#1 {main}
  thrown in C:\Users\ARTA\Desktop\laravel-blog\bootstrap\app.php on line 14

**Comment by guillaumebriday** [comment]
Did you run `composer install` first? 

It does not seem to be related to this project directly, right?

**Comment by rajsarky** [comment]
Hi, but it's still now loading:

php artisan migrate --seed                             

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'homestead' and table_type = 'BASE TABLE' order by table_name)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:822
    818▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    819▕                 );
    820▕             }
    821▕ 
  ➜ 822▕             throw new QueryException(
    823▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    824▕             );
    825▕         }
    826▕     }

      +39 vendor frames 

  40  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))



how can I fix this?

**Comment by guillaumebriday** [comment]
I think it's a problem with your environment, 

You can use Herd if you have some issues
