### ISSUE TITLE
[FEATURE REQUEST] select thumbnails from Unsplash

### ISSUE THREAD

**Issue by adenlall** [guillaumebriday/laravel-blog#158]
## Describe the Feature
Let the user select images on ``gallery`` or on ``create post`` page directly from Unsplash.

## Expected behavior
Ability of adding Thumbnail directly from ``create post`` page by search prompt that use Unsplash API.

## Additional context
I want to here your Feedback and I'am planning to work on it on a pull request.

**Comment by adenlall** [comment]
In additional to this I consider storing just the Unsplash URL of the Image not the Image itself so it can be fine on server usage

**Comment by guillaumebriday** [comment]
Hi

Thanks for the suggestion but this project is for educative purpose, to learn how to use Laravel in "real life". So I don't think we need this kind of feature!

Thanks!
