### ISSUE TITLE
str_slug can't handle Chinese, causing the post to fail to add

### ISSUE THREAD

**Issue by ivoth** [guillaumebriday/laravel-blog#16]
![_20180322194359](https://user-images.githubusercontent.com/14860741/37768673-6f290c3a-2e09-11e8-8292-74b1fbb4560d.png)
The slug field cannot be null, resulting in an article adding the second Chinese title.

**Comment by guillaumebriday** [comment]
🤔 I think the ```str_slug``` can't handle non ascii characters. 

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/Str.php#L418

Can you make a PR to fix it ?

Thanks

**Comment by ivoth** [comment]
This processing of Chinese needs to convert third-party translation APIs to English for use as URLs.
Now I can only temporarily id as a slug field.

I want to use this ID when slug is empty when I generate the url, but I can't seem to find it. please help me.
Thanks

**Comment by ivoth** [comment]
It is recommended to add the slug field to the form, but it is optional. If it is not filled, it is automatically generated so that it is compatible with Chinese.

**Comment by guillaumebriday** [comment]
Seems cool. I did the same behaviour with the media library and the name of images. 

I put it on the roadmap
