### ISSUE TITLE
Minor README.md and composer.json suggestion

### ISSUE THREAD

**Issue by markc** [guillaumebriday/laravel-blog#162]
Here is a suggestion for README.md (drop the $ so this section can be posted directly into a shell)...
```
git clone https://github.com/guillaumebriday/laravel-blog.git
cd laravel-blog
composer install
npm install
cp .env.example .env
touch database/database.sqlite
php artisan key:generate
php artisan storage:link
php artisan horizon:install
php artisan telescope:install
composer require laravel/pail
php artisan migrate:fresh --seed
composer run dev
```
and, in composer.json...
```
    "scripts": {
    ...
        ],
        "dev": [
            "Composer\\Config::disableProcessTimeout",
            "npx concurrently -k -c \"#93c5fd,#c4b5fd,#d4d4d8,#fdba74\" \"php artisan serve\" \"php artisan queue:listen --tries=1 --timeout=120\" \"php artisan pail\" \"npm run dev\" --names=server,queue,logs,vite"
        ]
    },
```

**Comment by guillaumebriday** [comment]
Hey! Thanks for the suggestion,

I'm not a huge fan of `npx concurrently`, and by default I suggest people to use Herd, so no need to `php artisan serve` here.

But I wasn't aware of `php artisan pail` and you should add it to the stack for sure 👍

**Comment by markc** [comment]
Unfortunately, some of us are stuck on linux systems where Herd is not available. I thought the point of this repo was so anyone could get from git clone to working demo with the least path of resistance, like simply pasting a dozen commands into a shell prompt and login.
