### ISSUE TITLE
Special char are allowed in registration

### ISSUE THREAD

**Issue by pifaace** [guillaumebriday/laravel-blog#19]
Hey !
I noticed that you authorize specials chars in your registration form, so I can put a username like "$ù$ù$^-"
I think you should not allow that ;)

**Comment by guillaumebriday** [comment]
Hey ! 

You're right, I fixed it. Thanks

here : https://github.com/guillaumebriday/laravel-blog/commit/0942a2beb2d00b701bd5be1ed599795ffdac2aad
