### ISSUE TITLE
Make time optional or pre-fill date/time.

### ISSUE THREAD

**Issue by libasoles** [guillaumebriday/laravel-blog#20]
It's a great job. Great case study. Thanks.

I'd suggest, regarding UX, to **autocomplete date/time** when creating a new post. Because we'd want to publish with today date most of the times. Also, _time_ may not be important for some of us. I don't really like to fill it, but it happens to be mandatory. Really, I'd just skip it. So, having it pre-filled would help on that, making it easy to just skip it. 

You know? After installing, removing the time from the front-end view it's trivial. Removing it from the admin maybe it's trivial too, but I'd tend not to touch the admin code. Usually, I'd just care about the frontend changes. And that leads me to another proposal: just like in wordpress, it would be nice to decouple the front-end theme. I mean, saving the views in a folder, and create a template selector in the admin area. It's just an idea. I don't know if you plan to make this grow.

**Comment by guillaumebriday** [comment]
Hey, thanks for your comment ! 👍 

And yep you're right, I'm going to do something to fix it anytime soon
