### ISSUE TITLE
MySQL Connection Refused AND SQLSTATE[HY000] with Docker 0.0.0.0 SQL

### ISSUE THREAD

**Issue by sovrinbloc** [guillaumebriday/laravel-blog#26]
![image](https://user-images.githubusercontent.com/2636997/39669582-cbaf8c6e-50a4-11e8-9d42-4495ee3f9237.png)

Inside `.env`, when I have the MySQL `DB_HOST=mysql`, and I try to run a migration, I get: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (SQL: select * from information_schema.tables where table_schema = laravel-blog and table_name = migrations)

![image](https://user-images.githubusercontent.com/2636997/39669586-e29e5112-50a4-11e8-85ad-8e1399f585a4.png)
But I am able to log in and out of the website, etc.

When I change the `DB_HOST=mysql` to `DB_HOST=0.0.0.0` I am able to run migrations but it throws a Cannot Connect error when I try to log in and out.

![image](https://user-images.githubusercontent.com/2636997/39669587-f2c364e2-50a4-11e8-8710-7a3e8579ec75.png)

When I try to log in
`Illuminate \ Database \ QueryException (2002)
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `users` where `email` = josephalai@gmail.com limit 1)
`

![image](https://user-images.githubusercontent.com/2636997/39669592-1fde2f20-50a5-11e8-9dfd-71d4a878e8ce.png)

https://paste.ofcode.org/Gkk4um4UuMy7d9iW2qmfyH

My docker...
![image](https://user-images.githubusercontent.com/2636997/39669596-5247cd40-50a5-11e8-9571-d06d7ca90aca.png)

**Comment by sovrinbloc** [comment]
The problem was that I had to add the following to `/etc/hosts` since the container is called `mysql` and it didn't know where to look. 

```
127.0.0.1 mysql
```

**Comment by guillaumebriday** [comment]
It works on the application because they share the same docker network.

You should not run the migrate command on your host but in other docker container if you don't want to change your `/etc/hosts` file
