### ISSUE TITLE
Images will not upload even when setting permissions in shell

### ISSUE THREAD

**Issue by sovrinbloc** [guillaumebriday/laravel-blog#27]
Following this guide, I still am not able to upload images.
https://stackoverflow.com/questions/30639174/file-permissions-for-laravel-5-and-others

Even when I pulled a 777, still, no uploaded image.

![image](https://user-images.githubusercontent.com/2636997/39669837-5b68eff6-50ac-11e8-8a8d-8150140855f9.png)

**Comment by sovrinbloc** [comment]
I messed up the config inadvertently

**Comment by guillaumebriday** [comment]
I added some documentation in the readme about the storage if needed 👍
