### ISSUE TITLE
Error deleting an image

### ISSUE THREAD

**Issue by Mathias88** [guillaumebriday/laravel-blog#28]
When you delete an image from the media it is not removed from the associated posts generating an error in the home.

**Comment by guillaumebriday** [comment]
Hey ! Thanks for your feedback 👍 

You're right, I will fix that today

**Comment by guillaumebriday** [comment]
🤔 I've just tried and everything seems to work fine.

In the migration, i've already added a `set null` on delete. https://github.com/guillaumebriday/laravel-blog/blob/master/database/migrations/2018_03_22_215224_create_media_table_with_media_library.php#L33

Can you give me more details ?

**Comment by Mathias88** [comment]
I went back to the test and now it worked. Maybe I had configured something wrong myself. Sorry.
