### ISSUE TITLE
Get thumbnail query getting executed multiple time

### ISSUE THREAD

**Issue by sumitparkash** [guillaumebriday/laravel-blog#3]
On the home page if you check in debugger bar you will find that the query to get the post thumbnail is getting executed multiple time . So if you have multiple post with thumbnail , then  2 query get executed per post to get thumbnail.

**Comment by sumitparkash** [comment]
As a solution i think you need to change the  thumbnail() function under the Post model. 

I think you can change the thumbnail() function

`return $this->media()->where('id', $this->thumbnail_id)->first();`  

to this 

`return $this->media->where('id', $this->thumbnail_id)->first();`

and you will find that the multiple query are not getting executed.

**Comment by guillaumebriday** [comment]
Hey ! 

Thank you very much for this issue !
You're absolutely right, in this commit (7720099) I added eager loading on the hasThumbnail method but I forgot to change the thumbnail one.

I'm fixing this.

**Comment by guillaumebriday** [comment]
733cc2db59975fd0544be1616ee17156b6df7615
