### ISSUE TITLE
Comment Echo not working

### ISSUE THREAD

**Issue by Mathias88** [guillaumebriday/laravel-blog#31]
Hi, me again. Comment posting is working but the Echo listen function does not work.

I have the commands npm star, artisan queue: work and redis running but the message does not reach the listen function.

In the console of nom star it shows the following:

> [12:36:00] - NA8nxWOwN-wyy5j6AAAB left channel: post.2 (transport close)
[12:36:01] - tDfTVxtoDfBjl0ICAAAD joined channel: post.2

And in the queue: work console it shows the following:

> [33m [2018-05-16 17:36:12] [VUe75mg1ITslY99WvAKfPJByWH63srwo] Processing: [39m App \ Events \ CommentPosted
[32m [2018-05-16 17:36:12] [VUe75mg1ITslY99WvAKfPJByWH63srwo] Processed: [39m App \ Events \ CommentPosted

I do not know what to review. Please help.

**Comment by guillaumebriday** [comment]
Hey ! I give it a shot and everything works fine. Can you give me more details ? Thanks

**Comment by sjeremic91** [comment]
I also have problem with this. Laravel Log says:
`
[2018-07-09 15:36:30] local.ERROR: Connection refused [tcp://redis:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 111): Connection refused [tcp://redis:6379] at /application/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]
#0 /application/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /application/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Parameters), 'tcp://redis:637...', 4)
#2 /application/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parameters))
#3 /application/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#4 /application/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()
#5 /application/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#6 /application/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
\7 /application/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamConnection->write('*6\
\5\
\MGET\
...')
#8 /application/vendor/predis/predis/src/Pipeline/Pipeline.php(133): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\HashGetMultiple))
#9 /application/vendor/predis/predis/src/Pipeline/Pipeline.php(165): Predis\\Pipeline\\Pipeline->executePipeline(Object(Predis\\Connection\\StreamConnection), Object(SplQueue))
#10 /application/vendor/predis/predis/src/Pipeline/Pipeline.php(214): Predis\\Pipeline\\Pipeline->flushPipeline()
#11 /application/vendor/predis/predis/src/Client.php(445): Predis\\Pipeline\\Pipeline->execute(Object(Closure))
#12 /application/vendor/predis/predis/src/Client.php(396): Predis\\Client->createPipeline(NULL, Object(Closure))
#13 /application/vendor/predis/predis/src/Client.php(418): Predis\\Client->sharedContextFactory('createPipeline', Array)
#14 /application/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(96): Predis\\Client->pipeline(Object(Closure))
#15 /application/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): Illuminate\\Redis\\Connections\\Connection->command('pipeline', Array)
#16 /application/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(77): Illuminate\\Redis\\Connections\\Connection->__call('pipeline', Array)
#17 /application/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(62): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->get(Array)
#18 /application/vendor/laravel/horizon/src/Console/HorizonCommand.php(42): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->find('6f51b4839f1a-zG...')
#19 [internal function]: Laravel\\Horizon\\Console\\HorizonCommand->handle()
#20 /application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /application/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /application/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#25 /application/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#26 /application/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /application/vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /application/vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\HorizonCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /application/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /application/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /application/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /application/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 {main}
"} 
`
