### ISSUE TITLE
PHPUnit Testing Fail?

### ISSUE THREAD

**Issue by sovrinbloc** [guillaumebriday/laravel-blog#32]
In trying to use phpunit inside any of the docker containers, I cannot. It yells at me to do a composer install but it mainly talks about how it can't find the current location. When I enter any besides nginx container, I get,  `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory` immediately when using `docker exec -it .../bin/bash`.

Do you have a way to do Unit tests?

Then when trying outside of docker and inside my local machine, no test passes. It seems like it is because I am not running the command from inside docker.
![image](https://user-images.githubusercontent.com/2636997/40266221-3aabc9c8-5afc-11e8-99bd-e6a4342b3ceb.png)
![image](https://user-images.githubusercontent.com/2636997/40266267-c40385bc-5afc-11e8-82e3-bb5bb873312f.png)

I'd possibly like to help with this project, as I am starting to use this as the base of one of my projects.

**Comment by guillaumebriday** [comment]
Hey ! It's look like its a duplication of https://github.com/guillaumebriday/laravel-blog/issues/25 ? Can you check ?

Thanks

**Comment by guillaumebriday** [comment]
I had the issue if I run the command `docker-compose run --rm blog-server ./vendor/bin/phpunit --stop-on-failure` before starting the mysql container.

This is so annoying but it's a duplication of #25.
