### ISSUE TITLE
DebugBar Should Be a Dev Composer Requirement

### ISSUE THREAD

**Issue by tompenzer** [guillaumebriday/laravel-blog#34]
Debugbar should be moved from the `composer.json`'s `require` section to the `require-dev` section, so people don't release it to production by mistake.

https://github.com/guillaumebriday/laravel-blog/blob/master/composer.json#L9

**Comment by tompenzer** [comment]
Edit: hmm, upon reflection, it's probably intended to be allowed to have Debugbar in production, and users should obviously be setting `APP_DEBUG=false` in `.env.production`.

**Comment by guillaumebriday** [comment]
Yes, by default Debuggar is disabled if the environnement is production.

But you're right, the documentation says :

> It is recommended to only require the package for development 

Feel free to open a PR.

Thanks
