### ISSUE TITLE
Feature proposals: non-social mode, contact form

### ISSUE THREAD

**Issue by tompenzer** [guillaumebriday/laravel-blog#36]
Hi Guillaume,

In modifying this project for my personal uses, a couple features seem like they might be appealing to users of the project for relatively little effort:

1) Add a `.env` variable for `SOCIAL_FEATURES=true`, and if you set it to `false`, self-registration routes are disabled, and commenting and liking are no longer rendered to the views or queried in the controllers. I've hard-coded most of those changes in my fork, but it would be relatively straightforward to add conditionality where needed keyed off the `.env` and make that a configuration option.

2) I've added a (fully localized) lightweight implementation of a contact form, implemented with a new 'Can be contacted' role assigned to users you want to appear in a recipient selector on the contact page if there are more than one user with the role. Upon submission, the form's post contents get emailed out to the corresponding user's email. Optionally, in my fork, I've also replaced the 'email' displayed on user profiles with a 'title' string column I added to the `users` table (in addition to a 'blurb' text column, and a media_id integer foreign key reference to a media gallery item for a profile pic), but an alternative might be to put a link to `contact.user, $user` there (a separate route for contacting a particular recipient, i.e. `/contact/user/1`). I say lightweight because the contact form submissions are neither stored in the DB, nor managed in the admin dashboard. They just get emailed right out and that's it.

I'd be happy to contribute these features if you'd be interested, though I'm ashamed to say I can't figure out how to submit a PR, since I can't make branches.

**Comment by tompenzer** [comment]
Oh wait, I guess I can fork it for that PR, and set that fork as the source for the PR... that must be how you do it. Lemme know if you're interested.

**Comment by guillaumebriday** [comment]
Hey ! Thank you so much for your contributions, I saw your fork, it's great !

This features could be very useful indeed but I don't think they belong to this project because the main purpose of this repo is to show how to use the framework features. This features seem to add complexity for non technical purpose.

I hope you understand, Thanks ! 👌
