### ISSUE TITLE
Remove alpha_dash validation restriction on User->name

### ISSUE THREAD

**Issue by tompenzer** [guillaumebriday/laravel-blog#37]
I can't figure out why there's an alpha-dash restriction on user names. Having full names with spaces seems fine. I've removed the `alpha_dash` rules in both the following places without incident:

https://github.com/guillaumebriday/laravel-blog/blob/master/app/Http/Requests/Admin/UsersRequest.php#L25

https://github.com/guillaumebriday/laravel-blog/blob/master/app/Http/Requests/UsersRequest.php#L25

Is there a reason not to allow spaces?

**Comment by guillaumebriday** [comment]
Hey !

I set `alpha_dash` because I think it's fine to prevent specials chars in the name. Spaces are not allowed with `alpha_dash` but it's not that bad because most of the time there is dashes in name instead of spaces.

**Comment by tompenzer** [comment]
But is there a problem caused by not having this rule?

**Comment by guillaumebriday** [comment]
There is no technical problem, I just want to prevent specials chars from a `name` 👍

**Comment by tompenzer** [comment]
I guess my view might be biased since I use the project mainly with self-registration disabled, and this is a kind of mitigation for XSS attacks if you make use of those usernames anywhere without proper `{{}}/e()` escaping. To me, that would seem like a steep usability price to pay, and I'd tend to just treat it like untrusted user input and not attempt to sanitize it to this extent.

**Comment by guillaumebriday** [comment]
Ok I see your point. I think a good compromise could be to extend Validation with an `alpha_dash_spaces` maybe ?

**Comment by tompenzer** [comment]
Oh, yeah! That would be a good improvement. I wasn't aware of that option. 

You might even consider having that in the normal UserRequest rules, and absent from Admin/UserRequest rules, since admins can be trusted to not enter malicious strings, if you're comfortable with the normal edit profile form throwing error if those users try to use it. I would assume there are many languages where common names will fail `alpha_dash_spaces`.

**Comment by tompenzer** [comment]
I'm not seeing `alpha_dash_spaces` listed as a standard Laravel validation rule ( https://laravel.com/docs/5.6/validation#rule-alpha-dash ). For something as personal and important as names, if you want to be internationalization-friendly, it might be best to use a blacklist of undesired characters rather than a whitelist of acceptable ones. That said, for English and most French names, `/[a-z\- ]+/i` is probably a decent shortcut.

**Comment by tompenzer** [comment]
If you're interested, I've successfully tested adding some custom rules you might find more appropriate for the purpose of user names in my project fork, and I'd be happy to submit a PR to merge them back upstream: 

https://github.com/tompenzer/penzone/commit/b721f78f4e3dfc479c6a171086ef4e1651798c88

I've looked into how best to address this scenario within the Laravel ecosystem, and it would appear  unlikely to me for such a feature PR to get accepted into `Illuminate/Validation` without an extensive set of tests and justifications. I'll maybe explore creating a small composer package for these rules, but pending that, this seems like a decent way to go about it.

**Comment by guillaumebriday** [comment]
yeah we need to create a custom validator for this use case. 

Your `AlphaName` one looks like what I wanted to do.

I will propose this PR if I find free time !

If you want to submit a PR for `AlphaName` laravel-blog, it could be awesome !

Thanks for your contribution

**Comment by guillaumebriday** [comment]
Done here : https://github.com/guillaumebriday/laravel-blog/pull/39
