### ISSUE TITLE
ERROR: for laravelblog_mysql_1  Cannot create container for service mysql: invalid bind mount spec "/home/laravel-blog/storage/tmp/db:/var/lib/mysql:cached": invalid mode: cached

### ISSUE THREAD

**Issue by rasperepodvipodvert** [guillaumebriday/laravel-blog#40]
After ```docker-compose run --rm --no-deps blog-server composer install```

```ERROR: for laravelblog_mysql_1  Cannot create container for service mysql: invalid bind mount spec "/home/laravel-blog/storage/tmp/db:/var/lib/mysql:cached": invalid mode: cached```

Run on:
```
[root@localhost laravel-blog]# docker -v
Docker version 1.13.1, build 30c1ca9-unsupported

[root@localhost laravel-blog]# docker-compose -v
docker-compose version 1.17.1, build 6d101fb
```

**Comment by guillaumebriday** [comment]
Hey, your both versions of Docker and Docker-compose are very old. 

The `1.13.1` version is the same as the `17.03` after the new versioning scheme.

To use the `cached` mode, you need at least `17.04`.

**Comment by rasperepodvipodvert** [comment]
Please write this in "Development environment requirements :"
Docker version >= 17.04

**Comment by guillaumebriday** [comment]
Done here, I added the stable version required https://github.com/guillaumebriday/laravel-blog/commit/4e58b56efeedbda7dc9ff48911e3b722dc1f331e
