### ISSUE TITLE
Doctrine\DBAL\Driver\PDOException:

### ISSUE THREAD

**Issue by demeus** [guillaumebriday/laravel-blog#42]
Hey ! When I run $ docker-compose run --rm blog-server php artisan migrate --seed
 I get the following error message: 

`Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `custom_properties` json not null, `responsive_images` json not n' at line 1") /private/var/www/laravel.local/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php : 82`

**Comment by guillaumebriday** [comment]
I do not succeed to reproduce the bug. Can you give me more details ?

thanks
