### ISSUE TITLE
add comment error

### ISSUE THREAD

**Issue by namdaik** [guillaumebriday/laravel-blog#47]
Comments are added but are not displayed immediately

**Comment by guillaumebriday** [comment]
hum, I need to refactor the [vuejs code to Vuex](https://github.com/guillaumebriday/laravel-blog/projects/2#card-12109718) but until then I think this behaviour is already the one you want.

Did you start redis and the echo server ?

**Comment by guillaumebriday** [comment]
Ok I think this commit https://github.com/guillaumebriday/laravel-blog/commit/7f635532c1d33d1e414b6bca430026173e4fd2af fix your issue
