### ISSUE TITLE
"419 Sorry, your session has expired": When trying to log in! 

### ISSUE THREAD

**Issue by sovrinbloc** [guillaumebriday/laravel-blog#51]
![image](https://user-images.githubusercontent.com/2636997/51069328-7cf88f00-15e1-11e9-9563-4c46937bf90d.png)

When trying to log in, it does not allow me to do so. This has not happened before. But it gives me a 419 and says, "Sorry your session has expired." 

Do you know how to fix this?

**Comment by guillaumebriday** [comment]
Hey ! Could you give me more details ? I tried on a fresh new clone and it worked fine.

thanks

**Comment by sovrinbloc** [comment]
I ran out of disk space. After slamming my head against the keyboard a few dozen times I must have evoked a response from the Linode to tell me I was out of space. I resized my Linode and it worked like a charm. By the way, are there email notifications when a post is added? Is there an option for that?
