### ISSUE TITLE
NOAUTH Authentication required.

### ISSUE THREAD

**Issue by sovrinbloc** [guillaumebriday/laravel-blog#52]
In the log file, `laravel.log`, this error continuously gets marked. It increases the log file size increasingly multiple times per second, taking up the entire size of the server. 

I went into the `redis` docker container, checked to see if there was a password, which there was not. 
Also, I checked if there were any configuration file for redis which would be requiring a password -- there is no configuration file. 

Do you have any idea why this could be? 
```
[2019-01-16 20:32:39] local.ERROR: NOAUTH Authentication required. {"exception":"[object] (Predis\\Response\\ServerException(code: 0): NOAUTH Authentication required. at /application/vendor/predis/predis/src/Client.php:370)
[stacktrace]
#0 /application/vendor/predis/predis/src/Client.php(335): Predis\\Client->onErrorResponse(Object(Predis\\Command\\ListLength), Object(Predis\\Response\\Error))
#1 /application/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ListLength))
#2 /application/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(114): Predis\\Client->__call('llen', Array)
#3 /application/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(214): Illuminate\\Redis\\Connections\\Connection->command('llen', Array)
```

**Comment by guillaumebriday** [comment]
Hum I do not find this error in production nor in development 🤔 

Did you set your redis variables like following ?

```ini
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
```
