### ISSUE TITLE
Unable to install on windows subsystem linux

### ISSUE THREAD

**Issue by rana01645** [guillaumebriday/laravel-blog#53]
It's become really tough to install and run this app on windows sub system linux with valet. It's giving 500 interenal server error :(

**Comment by rana01645** [comment]
Fixed it by following
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by guillaumebriday** [comment]
You don't need Laravel Valet to run this app but only Docker. You can use Docker for Windows if needed https://docs.docker.com/docker-for-windows/
