### ISSUE TITLE
can't install project

### ISSUE THREAD

**Issue by trongtri0705** [guillaumebriday/laravel-blog#56]
![screenshot 3](https://user-images.githubusercontent.com/13271068/52937456-b7e4a400-3391-11e9-826b-d3b8089a9a08.png)

**Comment by guillaumebriday** [comment]
I'm pretty sure that `:cached` actually does not work on windows, try to remove it in the `docker-compose.yml`

**Comment by Command-Conquer** [comment]
Impossible to set up in Windows... tried to remove the :cached in all lines in docker-composer.yml but not working... stucked in ...

docker-compose run --rm --no-deps blog-server php artisan storage:link
ErrorException 
symlink(): Protocol error

Im a newbie with docker... I understand the whole but not the :cached part.

Thanks for your work
