### ISSUE TITLE
Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by mesadhan** [guillaumebriday/laravel-blog#57]
when I visit http://localhost:8000/ then throw error

**UnexpectedValueException**
The stream or file "/application/storage/logs/laravel-2019-02-21.log" could not be opened: failed to open stream: Permission denied

**Comment by svitix** [comment]
crutch: `docker-compose run --rm --no-deps blog-server chmod -R 777 storage/`

**Comment by guillaumebriday** [comment]
You need the right write permissions on your host as well 👍
