### ISSUE TITLE
Include the  file permission chmod 777 command to the readme file

### ISSUE THREAD

**Issue by zvvysotskaya** [guillaumebriday/laravel-blog#59]
Hi,
You are creating a nice application.

Following your installation instructions, I was able to install your application on my PC.
At the beginning  I faced  UnexpectedValueException and running “docker-compose run --rm --no-deps blog-server chmod -R 777 storage/” helped and, right away, I got another Illuminate\Database\QueryException.  I got rid of it by seeding the DB . So, if we run a file permission, seed DB, and only then access the app, we should not get these exceptions. 
That’ why I have just proposed to include file permission chmod 777 command to the readme file, so that people would spend less time for installing your app. Also it would be nice to place seeding db before accessing the app.

**Comment by guillaumebriday** [comment]
Hey ! Thank you

I don't think configuring chmod with 777 is a good practice.

Maybe adding an info box saying corrects writes access must be configured before using the app could be enough ? 🤔

**Comment by zvvysotskaya** [comment]
Hi I am sorry for my late replay. Sure it would be better to access the app after seeding db. And I agree with you about chmod 777. On the other hand, without permission, we cannot move farther. So, that it would be good to get a permission an another way. Having created a data direction in the storage folder worked for me. Besides, there is something going wrong with docker itself it does not allow to make migration and seed db. I got sql exception on that too.
I have installed your app without docker containers, and it is running well. But during installation I met some difficulties too. I’ve just pulled request to ask you if you like the changes.

**Comment by guillaumebriday** [comment]
Hey, sorry for the late answer.

I think you've got issue with your write permission but it's not related to this project. I still think you shouldn't use chmod 777 but configure correctly the permission for the www-data and your docker users

Thanks
