### ISSUE TITLE
Issue displaying the card in chrome

### ISSUE THREAD

**Issue by mapyourown** [guillaumebriday/laravel-blog#6]
In chrome the way the posts are displaying are in one column. But in the other browsers, it is side by side. I google it and I found that setting orphans: 1; widows:1; in the .card_column, will fix this issue. It is more of a bootstrap issue than this code. May be it will help someone.

**Comment by guillaumebriday** [comment]
Hey ! Thanks for the feedback. 

And yep you're right ! I found this bug when I migrated to this masonry-grid system but I think I'm gonna wait for a fix from bootstrap.

https://github.com/twbs/bootstrap/issues/20925 is still opened so there is hope :)

**Comment by mapyourown** [comment]
Thanks, I will pull the recent code, and I hope it will not break some of
the change I made to it. Any way I have a very limited budget to have some
one as an advisor on a project. I am planning to do it in GraphQL, React,
and Relay with postgres or mongodb. Bit I am open to do it in Laravel too,
do you think you have some time to work on the project. We can discuss
detail if you have interest and you have free time.

Thanks,
Samson
