### ISSUE TITLE
use multiple docker containers instead of just one

### ISSUE THREAD

**Issue by vesper8** [guillaumebriday/laravel-blog#60]
Hi there! First of all this is not a bug so feel free to close it at any point.

I thank for your contribution with this project, I am at a time in my dev life where I am diving into containerization and trying to wrap my mind around many things such as Terraform, Nomad, Jenkins, CI and Ansible

I have it in my mind that as much as possible everything should be a container and containers should be running only one process. I'm still confused about this.. don't all contains housing web apps need to run Nginx at the very least? And for sure any php app needs to also run php.. which makes the minimum configuration for a Docker container housing a Laravel project to include Nginx + Php.

But Redis could be its own Docker container, and so could Mysql.. right? This is good practice.. a bit more overhead but if you ever wanted to scale and have 3 of each Mysql/Redis and only 2 web servers.. and load balance the whole thing.. then starting with each service as a separate container would be a good idea to prepare for the future. Do you agree here?

I am wondering.. how easily would it be to modify your package so that as many as possible docker containers are used. It should be as simple as splitting them off into multiple docker-compose files.. creating multiple images.. and then in the database.php of Laravel (or the .env file) adjust the hosts for redis and mysql ? Also you'd have to open up the right ports on the containers housing those

Would love to hear your thoughts

Also.. is this setup production ready? I mean.. can I deploy this docker to production and expect it to work? I'm still very confused how nginx does its magic here and how the outside world can access websites inside containers as easily as if they are installed on the base OS.

Thanks for your time!!

**Comment by guillaumebriday** [comment]
Hey ! 

I'm confused about your comment because this project actually uses a single container per service as you suggest.

This setup is ready for production because it's already containerised 👍 

I use a very close configuration setup in this project https://github.com/guillaumebriday/todolist-backend-laravel in production if you want to take a look.

What do you want me to change in this project ?

Thank you

**Comment by vesper8** [comment]
thank you for your comment! At the time that I opened this issue it was still very early in my learning of Docker. I'm a little further ahead now and I understand now how the docker compose creates multiple containers.

I appreciate your project it's very helpful for learning with! I will close this issue now. Cheers!

**Comment by guillaumebriday** [comment]
No problem, thank you !
