### ISSUE TITLE
The stream or file "/application/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by stevensherah** [guillaumebriday/laravel-blog#63]
am getting this error after a successful intall on ubuntu xenial.

**Comment by stevensherah** [comment]
I have also added the permision on the storage folder and the particular /application/storage/logs/laravel.log file itself also and to no avail so far.

**Comment by IsiRoca** [comment]
Try this:

docker-compose run --rm --no-deps blog-server php artisan cache:clear
docker-compose run --rm --no-deps blog-server chmod -R 777 storage/
docker-compose run --rm --no-deps blog-server composer dump-autoload

**Comment by guillaumebriday** [comment]
thank you @IsiRoca
