### ISSUE TITLE
Erro on create a new post

### ISSUE THREAD

**Issue by pedrosoares** [guillaumebriday/laravel-blog#7]
The rule "'slug' => 'unique:posts,slug,' . optional($this->post)->id," is create an exception because the id is empty.
Database: postgresql

**Comment by guillaumebriday** [comment]
Hey ! Thanks for reporting a bug 🙂 

I don't use postgresql for this project, could you submit a PR to fix it if possible ? Because it works fine with MySQL.

Thanks
