### ISSUE TITLE
Blog link isn't valid (README)

### ISSUE THREAD

**Issue by Sogl** [guillaumebriday/laravel-blog#80]
This link I can't open everywhere: https://blog.guillaumebriday.fr/

**Comment by guillaumebriday** [comment]
Fix here : https://github.com/guillaumebriday/laravel-blog/commit/b2707f8155809845b3694442fc5484f11259b5d1

Thank you !

**Comment by Sogl** [comment]
Haha, but where I can read details now? 😄

**Comment by guillaumebriday** [comment]
There is no details on my blog yet haha
