### ISSUE TITLE
If user change email in profile, we need to send new verify mail

### ISSUE THREAD

**Issue by Sogl** [guillaumebriday/laravel-blog#90]
Need to check if new email is valid.

Any ideas?

**Comment by guillaumebriday** [comment]
Hey @Sogl, thank you for your suggestion.

I think Laravel implemented this functionality only on create also to prevent bot to create thousands of records in your database for nothing.

I don’t remember the last time a service ask me to verify my email address on an update, do you have an example? If the email is wrong you can still change it again if you’re log in, right?

Thank you

**Comment by Sogl** [comment]
It can be a problem when you use users table as a mail list and other situations when you need a valid e-mail address. 

Situation:
1) user typed a valid e-mail and registered it
2) he changed it to bill@gates.com or made a mistake in e-mail change
3) after some time you send e-mail in subscribe list to wrong address 
4) in typo: user can't log-in because password reset link sent to wrong address

In step two we can block user actions before email confirmation

**Comment by ibnuh** [comment]
This is interesting, probably including the email address as the part of the token, then decrypt while it's used?

**Comment by guillaumebriday** [comment]
Ok it seems cool, feel free to open a PR, I don't have the time to develop this feature :/

Thank you
