### ISSUE TITLE
Post Feed Image Conversions

### ISSUE THREAD

**Issue by ThatGuyMelo** [guillaumebriday/laravel-blog#97]
Having trouble displaying the "conversion" image on the "posts feed" card in any related view.

Upon further inspection i realize that when uploading images to the gallery, they get stored perfectly in https://example.com/storage/x/123.jpg but for some reason when publishing posts, the thumbnail image does not get stored in what should evidently be https://example.com/storage/x/conversions/123.-thumb.000jpg 

Could this somehow be related to my permissions - which i doubt; or is it something else? Please kindly advice on how i can resolve it...

P.S: I would suggest a link in admin below "edit thumbnail image" to the path of the actual thumbnail, similar to the gallery setup; all issues apart, you've done an exceptional job. Thanks

**Comment by DungBuiDeveloper** [comment]
same IS

**Comment by guillaumebriday** [comment]
Hum, I will check it out,

Open a PR if you find a solution please

Thank you

**Comment by guillaumebriday** [comment]
I fix it in https://github.com/guillaumebriday/laravel-blog/commit/f25a6374fcfc4ae37743b034e56f093dc06ec6f0 

Thank you guys !
