### ISSUE TITLE
[BUG]  Syntax error or access violation: 1064 You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by nomadtechiemike** [guillaumebriday/laravel-blog#99]
**Please read the README before considering opening an issue and be sure to check that the bug is not related to your development environment. It's ok if you don't want to use Docker but you must know what you're doing.** 

## Describe the bug
Trying to run sudo php artisan migrate --seed

## To Reproduce
 at /var/www/html/laravel-blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `custom_properties` json not null, `responsive_images` json not n' at line 1")
      /var/www/html/laravel-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `custom_properties` json not null, `responsive_images` json not n' at line 1")
      /var/www/html/laravel-blog/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

**Comment by guillaumebriday** [comment]
Hey, 

It seems like you don't use the provided development environment. You use MariaDB which I never worked with so I can't help you.

Check your DB_HOST variable and your database.php config.
